server:
  port: {SERVER_PORT:8080}
  isProduction: {IS_PRODUCTION:false} 

auth:
  github:
    clientId: {GITHUB_KEY:}
    clientSecret: {GITHUB_SECRET:}
    clientScope: {GITHUB_SCOPE:user}
    responseType: {GITHUB_RESPONSE_TYPE:code}
    accessType: {GITHUB_ACCESS_TYPE:offline}
    grantType: {GITHUB_GRANT_TYPE:authorization_code}
    callback: {GITHUB_CALLBACK:http://localhost:8080/auth/github/callback}
    authUrl: {GITHUB_AUTH_URL:https://github.com/login/oauth/authorize}
    tokenUrl: {GITHUB_TOKEN_URL:https://github.com/login/oauth/access_token}
    userUrl: {GITHUB_USER_URL:https://api.github.com/user}

  google:
    clientId: {GOOGLE_KEY:}
    clientSecret: {GOOGLE_SECRET:}
    clientScope: {GOOGLE_SCOPE:https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile}
    responseType: {GITHUB_RESPONSE_TYPE:code}
    accessType: {GITHUB_ACCESS_TYPE:offline}
    grantType: {GITHUB_GRANT_TYPE:authorization_code}
    callback: {GOOGLE_CALLBACK:http://localhost:8080/auth/google/callback}
    authUrl: {GOOGLE_AUTH_URL:https://accounts.google.com/o/oauth2/v2/auth}
    tokenUrl: {GOOGLE_TOKEN_URL:https://oauth2.googleapis.com/token}
    userUrl: {GOOGLE_USER_URL:https://www.googleapis.com/oauth2/v2/userinfo}

db:
  host: {DB_HOST:}
  port: {DB_PORT:}
  database: {DB_NAME:}
  username: {DB_USER:}
  password: {DB_PASSWORD:}
