/*
 * This source file was generated by the Gradle 'init' task
 */
package io.jawisp.example;

import org.junit.jupiter.api.Test;

import io.jawisp.example.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
